table DimGeography

	column GeographyKey
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column StateProvinceCode
		dataType: string
		summarizeBy: none
		sourceColumn: StateProvinceCode

		annotation SummarizationSetBy = Automatic

	column StateProvinceName
		dataType: string
		summarizeBy: none
		sourceColumn: StateProvinceName

		annotation SummarizationSetBy = Automatic

	column CountryRegionCode
		dataType: string
		summarizeBy: none
		sourceColumn: CountryRegionCode

		annotation SummarizationSetBy = Automatic

	column EnglishCountryRegionName
		dataType: string
		summarizeBy: none
		sourceColumn: EnglishCountryRegionName

		annotation SummarizationSetBy = Automatic

	column SpanishCountryRegionName
		dataType: string
		summarizeBy: none
		sourceColumn: SpanishCountryRegionName

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column IpAddressLocator
		dataType: string
		summarizeBy: none
		sourceColumn: IpAddressLocator

		annotation SummarizationSetBy = Automatic

	partition DimGeography = m
		mode: import
		queryGroup: Consultas
		source =
				let
				    Origen = Sql.Databases("localhost\SQLEXPRESS"),
				    AdventureWorksDW2019 = Origen{[Name="AdventureWorksDW2019"]}[Data],
				    dbo_DimGeography = AdventureWorksDW2019{[Schema="dbo",Item="DimGeography"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(dbo_DimGeography,{"DimCustomer", "DimReseller", "DimSalesTerritory", "FrenchCountryRegionName"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación
