table DimPromotion

	column PromotionKey
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column PromotionAlternateKey
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: PromotionAlternateKey

		annotation SummarizationSetBy = Automatic

	column EnglishPromotionName
		dataType: string
		summarizeBy: none
		sourceColumn: EnglishPromotionName

		annotation SummarizationSetBy = Automatic

	column SpanishPromotionName
		dataType: string
		summarizeBy: none
		sourceColumn: SpanishPromotionName

		annotation SummarizationSetBy = Automatic

	column DiscountPct
		dataType: double
		summarizeBy: sum
		sourceColumn: DiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EnglishPromotionType
		dataType: string
		summarizeBy: none
		sourceColumn: EnglishPromotionType

		annotation SummarizationSetBy = Automatic

	column SpanishPromotionType
		dataType: string
		summarizeBy: none
		sourceColumn: SpanishPromotionType

		annotation SummarizationSetBy = Automatic

	column EnglishPromotionCategory
		dataType: string
		summarizeBy: none
		sourceColumn: EnglishPromotionCategory

		annotation SummarizationSetBy = Automatic

	column SpanishPromotionCategory
		dataType: string
		summarizeBy: none
		sourceColumn: SpanishPromotionCategory

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: StartDate

		variation Variación
			isDefault
			relationship: d7734776-b3a1-49b2-95dc-c45e0c6f995c
			defaultHierarchy: LocalDateTable_f44168f4-c672-4529-9dbe-f903bfdd2a84.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: EndDate

		variation Variación
			isDefault
			relationship: 96423fb3-67f7-4009-af0b-7a942ccd113a
			defaultHierarchy: LocalDateTable_0b84b9ce-0744-4199-8d85-1e3a38c20eb3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column MinQty
		dataType: double
		formatString: 0
		summarizeBy: sum
		sourceColumn: MinQty

		annotation SummarizationSetBy = Automatic

	column MaxQty
		dataType: double
		formatString: 0
		summarizeBy: sum
		sourceColumn: MaxQty

		annotation SummarizationSetBy = Automatic

	partition DimPromotion = m
		mode: import
		queryGroup: Consultas
		source =
				let
				    Origen = Sql.Databases("localhost\SQLEXPRESS"),
				    AdventureWorksDW2019 = Origen{[Name="AdventureWorksDW2019"]}[Data],
				    dbo_DimPromotion = AdventureWorksDW2019{[Schema="dbo",Item="DimPromotion"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(dbo_DimPromotion,{"FactInternetSales", "FactResellerSales", "FrenchPromotionName", "FrenchPromotionType", "FrenchPromotionCategory"}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas quitadas",null,0,Replacer.ReplaceValue,{"MaxQty"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado",{{"MinQty", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación
