table DimSalesTerritory

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryAlternateKey
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: SalesTerritoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryRegion
		dataType: string
		summarizeBy: none
		sourceColumn: SalesTerritoryRegion

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryCountry
		dataType: string
		summarizeBy: none
		sourceColumn: SalesTerritoryCountry

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryGroup
		dataType: string
		summarizeBy: none
		sourceColumn: SalesTerritoryGroup

		annotation SummarizationSetBy = Automatic

	partition DimSalesTerritory = m
		mode: import
		queryGroup: Consultas
		source =
				let
				    Origen = Sql.Databases("localhost\SQLEXPRESS"),
				    AdventureWorksDW2019 = Origen{[Name="AdventureWorksDW2019"]}[Data],
				    dbo_DimSalesTerritory = AdventureWorksDW2019{[Schema="dbo",Item="DimSalesTerritory"]}[Data],
				    #"Columnas quitadas" = Table.RemoveColumns(dbo_DimSalesTerritory,{"DimEmployee", "DimGeography", "FactInternetSales", "FactResellerSales"}),
				    #"Filas filtradas" = Table.SelectRows(#"Columnas quitadas", each ([SalesTerritoryKey] <> 11))
				in
				    #"Filas filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación
